import LightedCube from './LightedCube'
import LightedCube_ambient from './LightedCube_ambient'
import LightedCube_animation from './LightedCube_animation'
import LightedCube_perFragment from './LightedCube_perFragment'
import LightedTranslatedRotatedCube from './LightedTranslatedRotatedCube'
import PointLightedCube from './PointLightedCube'
import PointLightedCube_animation from './PointLightedCube_animation'
import PointLightedCube_perFragment from './PointLightedCube_perFragment'
import PointLightedSphere from './PointLightedSphere'
import PointLightedSphere_perFragment from './PointLightedSphere_perFragment'
export {LightedCube,LightedCube_ambient,LightedCube_animation,LightedCube_perFragment,LightedTranslatedRotatedCube,PointLightedCube,PointLightedCube_animation,PointLightedCube_perFragment,PointLightedSphere,PointLightedSphere_perFragment}
